# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - chatindia-backend

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/dev_chatindia-backend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Build
        run: npm run build
        working-directory: backend

      - name: Prepare deployment package
        run: |
          cd backend
          mkdir -p deployment
          cp -r dist deployment/
          cp -r node_modules deployment/
          cp package.json deployment/
          cp package-lock.json deployment/
          cd deployment
          zip -r ../deployment.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24E6FDB744D94B4B8B653EF78C4BAD5C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B4E82C2EEE274C08ADF692E51F8256E5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C18B96F8FBAD4CFFB06EBEE9DDA81379 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatindia-backend'
          slot-name: 'Production'
          package: 'backend/deployment.zip'